### ISSUE TITLE
Expected FlutterAnnotation but found MKUserLocation

### ISSUE THREAD

**Issue by lucascolli** [LuisThein/flutter_platform_maps#1]
Hello!

We are looking at using your package to gain access to the platform's native maps with as little platform-specific code as possible, and it should be very useful for us so thanks!

However I am getting the following error (iOS):
`Expected FlutterAnnotation but found MKUserLocation: file /BuildRoot/Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-1100.2.259.70/swift/stdlib/public/core/ArrayBuffer.swift, line 354`

when myLocationEnabled is set to true.

Usage:
<img width="491" alt="Screen Shot 2019-11-06 at 3 22 31 PM" src="https://user-images.githubusercontent.com/47360587/68335355-4b8a0c00-00aa-11ea-81e8-17c66d6eb9af.png">

Please let me know if this can be resolved. I also wouldn't mind contributing if pointed in the right direction. Thanks!

EDIT: An additional piece of info - the initial rendering of the map works, but a subsequent rebuild of the widget causes a crash.

**Comment by LuisThein** [comment]
Thanks for reporting this issue, I'm looking into it.
This seems to be an issue with [apple_maps_flutter]("https://github.com/LuisThein/apple_maps_flutter"), I will let you know if I find out something new.

**Comment by LuisThein** [comment]
I think I found the problem, there was an issue with updating the Apple Map Annotations (aka Markers) when rebuilding the Widget.
The issue should be resolved with version 0.1.4 of flutter_platform_maps.
