### ISSUE TITLE
PlatformException(error, Attempt to invoke virtual method 'float java.lang.Number.floatValue()' on a null object reference, null)

### ISSUE THREAD

**Issue by lucascolli** [LuisThein/flutter_platform_maps#2]
Hello!

After upgrading to 0.1.4, I am receiving a platform exception when the view is created. It appears to be Android only. Here is the stacktrace:

> E/MethodChannel#flutter/platform_views( 7589): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:87)
E/MethodChannel#flutter/platform_views( 7589): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:51)
E/MethodChannel#flutter/platform_views( 7589): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#flutter/platform_views( 7589): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#flutter/platform_views( 7589): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:656)
E/MethodChannel#flutter/platform_views( 7589): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter/platform_views( 7589): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#flutter/platform_views( 7589): 	at android.os.Looper.loop(Looper.java:174)
E/MethodChannel#flutter/platform_views( 7589): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/MethodChannel#flutter/platform_views( 7589): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform_views( 7589): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/MethodChannel#flutter/platform_views( 7589): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/flutter ( 7589): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'float java.lang.Number.floatValue()' on a null object reference, null)
E/flutter ( 7589): #0      StandardMethodCodec.decodeEnvelope 
package:flutter/…/services/message_codecs.dart:569
E/flutter ( 7589): #1      MethodChannel.invokeMethod 
package:flutter/…/services/platform_channel.dart:316
E/flutter ( 7589): <asynchronous suspension>
E/flutter ( 7589): #2      AndroidViewController._create 
package:flutter/…/services/platform_views.dart:640
E/flutter ( 7589): <asynchronous suspension>
E/flutter ( 7589): #3      AndroidViewController.setSize 
package:flutter/…/services/platform_views.dart:557
E/flutter ( 7589): <asynchronous suspension>
E/flutter ( 7589): #4      RenderAndroidView._sizePlatformView 
package:flutter/…/rendering/platform_view.dart:174
E/flutter ( 7589): <asynchronous suspension>
E/flutter ( 7589): #5      RenderAndroidView.performResize 
package:flutter/…/rendering/platform_view.dart:155
E/flutter ( 7589): #6      RenderObject.layout 
package:flutter/…/rendering/object.dart:1686
E/flutter ( 7589): #7      RenderStack.performLayout 
package:flutter/…/rendering/stack.dart:549
E/flutter ( 7589): #8      RenderObject.layout 
package:flutter/…/rendering/object.dart:1701
E/flutter ( 7589): #9      MultiChildLayoutDelegate.layoutChild 
package:flutter/…/rendering/custom_layout.dart:142
E/flutter ( 7589): #10     _ScaffoldLayout.performLayout 
package:flutter/…/material/scaffold.dart:444
E/flutter ( 7589): #11     MultiChildLayoutDelegate._callPerformLayout 
package:flutter/…/rendering/custom_layout.dart:212
E/flutter ( 7589): #12     RenderCustomMultiChildLayoutBox.performLayout 
package:flutter/…/rendering/custom_layout.dart:356
E/flutter ( 7589): #13     RenderObject.layout 
package:flutter/…/rendering/object.dart:1701
E/flutter ( 7589): #14     RenderProxyBoxMixin.performLayout 
package:flutter/…/rendering/proxy_box.dart:105
E/flutter ( 7589): #15     RenderObject.layout 
package:flutter/…/rendering/object.dart:17

Thanks!

**Comment by LuisThein** [comment]
Thanks for reporting the bug, I'm currently looking into that. An update fixing this and some other minor bugs will come very soon!

**Comment by LuisThein** [comment]
Hey, I just released version 0.1.4+1 which should fix this issue.

**Comment by lucascolli** [comment]
> Hey, I just released version 0.1.4+1 which should fix this issue.

Thanks, verified!
