### ISSUE TITLE
Custom markers not working on iOS

### ISSUE THREAD

**Issue by lucascolli** [LuisThein/flutter_platform_maps#3]
Hey again! I apologize if it seems like I'm opening an issue each time one closes - I appreciate your diligence!

I upgraded to 0.1.4+1 and added custom markers, but they only seem to show up on Android devices. On iOS devices, the default marker is still used. This was verified on an iPhone 8 Plus (simulator) and iPhone 6s Plus (physical).

**Usage**

`var _markerIcon;`

```
void _createMarkerFromImageAsset(BuildContext context) async {
    if(_markerIcon == null) {
      final ImageConfiguration imageConfiguration = createLocalImageConfiguration(context);
      var _markerBitmapDescriptor = await BitmapDescriptor.fromAssetImage(
        imageConfiguration, constants.markerImagePath
      ).catchError(print);
      setState(() {
        _markerIcon = _markerBitmapDescriptor;
      });
    }
  }
```

In the build method:
`_createMarkerFromImageAsset(context);`

Called when a successful response from our API is obtained:
```
void _addMarkers() {
    Set<Marker> _m = {};
    for(Store store in stores) {
      _m.add(
        Marker(
          icon: _markerIcon,
          markerId: MarkerId('$storeId'),
          position: LatLng(
            store.latitude, store.longitude
          ),
          consumeTapEvents: true,
          onTap: () => _toStoreDetails(store),
        ),
      );
    }
    setState(() {
      _markers = _m;
    });
}
```

Thanks!

**Comment by LuisThein** [comment]
No Problem, thanks for reporting these issues!
I will have a Look at that.

**Comment by lucascolli** [comment]
After further testing it looks like this may be my own issue. The custom markers sometimes appear on the map when navigating away and back to the screen. I'll make some changes to ensure my BitmapDescriptor is created before the markers are added to the map, and then I'll close this if it's resolved!

**Comment by lucascolli** [comment]
There may be something odd going on, as I haven't been able to produce consistent behavior on iOS. Unless there's something I'm not doing correctly to accommodate how the Apple Map loads. Would you be able to add an example with custom markers?

**Comment by LuisThein** [comment]
I was able to reproduce the behavior you describe, the custom marker doesn't load consistently. I'm currently changing the initialization of the custom marker icons in the apple_maps_flutter plugin. This issue should be hopefully resolved as soon as the next version of the apple_maps_flutter is released. 

Here is an example of how it should work:

```dart
import 'package:flutter/material.dart';
import 'package:platform_maps_flutter/platform_maps_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Custom Marker Demo',
      theme: ThemeData(
        accentColor: Colors.blue,
      ),
      home: CustomMarker(),
    );
  }
}

class CustomMarker extends StatefulWidget {
  const CustomMarker();

  @override
  State<StatefulWidget> createState() => CustomMarkerState();
}

const LatLng _kMapCenter = LatLng(52.4478, -3.5402);

class CustomMarkerState extends State<CustomMarker> {
  PlatformMapController controller;
  dynamic _markerIcon;

  @override
  Widget build(BuildContext context) {
    _createAnnotationImageFromAsset(context);
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        title: Text('Custom Marker example'),
      ),
      body: Column(
        mainAxisAlignment: MainAxisAlignment.spaceEvenly,
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: <Widget>[
          Center(
            child: SizedBox(
              width: 350.0,
              height: 300.0,
              child: PlatformMap(
                initialCameraPosition: const CameraPosition(
                  target: _kMapCenter,
                  zoom: 7,
                ),
                markers: _createAnnotation(),
                onMapCreated: _onMapCreated,
              ),
            ),
          ),
          Padding(
            padding: const EdgeInsets.all(20),
            child: FlatButton(
              child: Text('Reload'),
              onPressed: () => setState(() {}),
            ),
          )
        ],
      ),
    );
  }

  Set<Marker> _createAnnotation() {
    return <Marker>[
      Marker(
        markerId: MarkerId("annotation_1"),
        position: _kMapCenter,
        icon: _markerIcon,
      ),
    ].toSet();
  }

  Future<void> _createAnnotationImageFromAsset(BuildContext context) async {
    if (_markerIcon == null) {
      final ImageConfiguration imageConfiguration =
          createLocalImageConfiguration(context);
      BitmapDescriptor.fromAssetImage(
              imageConfiguration, 'assets/red_square.png')
          .then(_updateBitmap);
    }
  }

  void _updateBitmap(dynamic bitmap) {
    setState(() {
      _markerIcon = bitmap;
    });
  }

  void _onMapCreated(PlatformMapController controllerParam) {
    setState(() {
      controller = controllerParam;
    });
  }
}
```

**Comment by lucascolli** [comment]
> I was able to reproduce the behavior you describe, the custom marker doesn't load consistently. I'm currently changing the initialization of the custom marker icons in the apple_maps_flutter plugin. This issue should be hopefully resolved as soon as the next version of the apple_maps_flutter is released.
> 
> Here is an example of how it should work:
> 
> ```dart
> import 'package:flutter/material.dart';
> import 'package:platform_maps_flutter/platform_maps_flutter.dart';
> 
> void main() => runApp(MyApp());
> 
> class MyApp extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       title: 'Custom Marker Demo',
>       theme: ThemeData(
>         accentColor: Colors.blue,
>       ),
>       home: CustomMarker(),
>     );
>   }
> }
> 
> class CustomMarker extends StatefulWidget {
>   const CustomMarker();
> 
>   @override
>   State<StatefulWidget> createState() => CustomMarkerState();
> }
> 
> const LatLng _kMapCenter = LatLng(52.4478, -3.5402);
> 
> class CustomMarkerState extends State<CustomMarker> {
>   PlatformMapController controller;
>   dynamic _markerIcon;
> 
>   @override
>   Widget build(BuildContext context) {
>     _createAnnotationImageFromAsset(context);
>     return Scaffold(
>       backgroundColor: Colors.white,
>       appBar: AppBar(
>         title: Text('Custom Marker example'),
>       ),
>       body: Column(
>         mainAxisAlignment: MainAxisAlignment.spaceEvenly,
>         crossAxisAlignment: CrossAxisAlignment.stretch,
>         children: <Widget>[
>           Center(
>             child: SizedBox(
>               width: 350.0,
>               height: 300.0,
>               child: PlatformMap(
>                 initialCameraPosition: const CameraPosition(
>                   target: _kMapCenter,
>                   zoom: 7,
>                 ),
>                 markers: _createAnnotation(),
>                 onMapCreated: _onMapCreated,
>               ),
>             ),
>           ),
>           Padding(
>             padding: const EdgeInsets.all(20),
>             child: FlatButton(
>               child: Text('Reload'),
>               onPressed: () => setState(() {}),
>             ),
>           )
>         ],
>       ),
>     );
>   }
> 
>   Set<Marker> _createAnnotation() {
>     return <Marker>[
>       Marker(
>         markerId: MarkerId("annotation_1"),
>         position: _kMapCenter,
>         icon: _markerIcon,
>       ),
>     ].toSet();
>   }
> 
>   Future<void> _createAnnotationImageFromAsset(BuildContext context) async {
>     if (_markerIcon == null) {
>       final ImageConfiguration imageConfiguration =
>           createLocalImageConfiguration(context);
>       BitmapDescriptor.fromAssetImage(
>               imageConfiguration, 'assets/red_square.png')
>           .then(_updateBitmap);
>     }
>   }
> 
>   void _updateBitmap(dynamic bitmap) {
>     setState(() {
>       _markerIcon = bitmap;
>     });
>   }
> 
>   void _onMapCreated(PlatformMapController controllerParam) {
>     setState(() {
>       controller = controllerParam;
>     });
>   }
> }
> ```

Awesome, I'll keep an eye out for your next release of the Apple Maps plugin. Thanks for taking the time to reproduce and investigate this! I

**Comment by LuisThein** [comment]
I released a new version of the apple_maps_flutter package which should fix the custom marker icon initialisation, I wasn't able to reproduce the issue afterwards, please let me know if that fixed the problem for you.

**Comment by lucascolli** [comment]
Solved, thanks!
