### ISSUE TITLE
BitmapDescriptor.fromBytes

### ISSUE THREAD

**Issue by aloisdeniel** [LuisThein/flutter_platform_maps#6]
Hi,

I currently use custom marker images generated at runtime with the google map plugin from the `BitmapDescriptor.fromBytes` method.

Is there any blocking api on the Apple side ? If not, I could I help implement this for Apple maps.

**Comment by LuisThein** [comment]
As far as I know this should not be a problem, but still has to be implemented in the [apple_maps_flutter](https://github.com/LuisThein/apple_maps_flutter) package, which is planned to happen within the next month. If you want to contribute feel free to make a pull request with the required changes there and it will be implemented in this package as well.
